version: "3.9"

services:
  app:
    build: .
    image: tracker-app
    profiles:
      - prod
    container_name: tracker-app
    restart: unless-stopped
    depends_on:
      - db
      - rabbitmq-m
    env_file:
      - .env
    environment:
      DATASOURCE_URL:
      DATASOURCE_USERNAME:
      DATASOURCE_PASSWORD:
      SPRING_RABBITMQ_HOST:
      SPRING_RABBITMQ_USERNAME:
      SPRING_RABBITMQ_PASSWORD:
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_TEST_TO:
    ports:
      - "8080:8080"

  db:
    image: postgres:14.4
    container_name: postgres
    profiles:
      - prod
      - dev
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"

  rabbitmq-m:
    image: rabbitmq:3-management
    container_name: rabbitmq-m
    restart: unless-stopped
    profiles:
      - prod
      - dev
    ports:
      - "15672:15672"
      - "5672:5672"
