spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker
    username: user
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-root.xml
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties.mail.smtp.starttls.enable: true

springdoc:
  version: 0.0.1
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method

custom:
  security:
    permit-all: /swagger-ui/**, /v3/api-docs/**
  mail:
    enable: false
    test:
      enable: true
      to: ${SMTP_TEST_TO}
