# DAO -----------------------------
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-root.xml
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true