spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker
    username: user
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-root.xml
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties.mail.smtp.starttls.enable: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          multiplier: 2
          max-interval: 10000
          max-attempts: 3
#        default-requeue-rejected: false

springdoc:
  version: 0.0.1
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method

custom:
  security:
    permit-all: /swagger-ui/**, /v3/api-docs/**, /send/**
  mail:
    enable: false
    test:
      enable: true
      to: ${SMTP_TEST_TO}
  amqp:
    mail-exchange: mail.exchange
    mail-dl-exchange: mail.dl.exchange
    mail-queue: mail.queue
    mail-dl-queue: mail.dl.queue
